driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[test::single_node]
