AllCops:
  Excludes:
    - vendor/**
    - tmp/**
    - cookbooks/**
    - bin/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
StringLiterals:
  Enabled: false
NumericLiterals:
  MinDigits: 12
MethodLength:
  Max: 30

