name             'graphite'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures graphite'
source_url       'https://github.com/sous-chefs/graphite'
issues_url       'https://github.com/sous-chefs/graphite/issues'
version          '1.3.11'
chef_version     '>= 15.3'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'oracle'

depends  'poise-python', '>= 1.5'
