---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      checks: write
      pull-requests: write
      statuses: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "debian-12"
          - "ubuntu-2204"
          - "ubuntu-2404"
        suite:
          - "default"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Chef
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
